name: layer-by-layer
channels:
  - defaults
dependencies:
  - pip=21.3.1
  - python=3.10.13
  - pyyaml
  - readline
  - requests
  - setuptools
  - wheel
  - pip:
    - accelerate==0.27.2
    - datasets==2.17.1
    - einops==0.7.0
    - fastapi==0.109.2
    - gradio==3.50.2
    - gradio-client==0.6.1
    - huggingface-hub==0.20.3
    - jieba==0.42.1
    - numpy==1.26.4
    - matplotlib==3.8.3
    - pandas==2.2.1
    - peft==0.8.2
    - protobuf==4.25.3
    - nltk==3.8.1
    - rouge-chinese==1.0.3
    - safetensors==0.4.2
    - scipy==1.12.0
    - seaborn==0.12.2
    - sentencepiece==0.2.0
    - statsmodels==0.13.5
    - sse-starlette==2.0.0
    - tensorly==0.7.0
    - tokenizers==0.15.2
    - torch==2.2.1
    - torchaudio==2.2.1
    - torchvision==0.17.1
    - transformers==4.37.2
    - tqdm==4.66.2
    - trl==0.7.11
    - uvicorn==0.27.1
  
      
      
      
      



